spring:
  main:
    banner-mode: "off"
  shell:
    command:
      clear:
        enabled: true
      exit:
        enabled: true
      quit:
        enabled: true
      stacktrace:
        enabled: true
    interactive:
      enabled: true
logging:
  level:
    root: INFO
  file: cli-appl.log
  pattern:
    console: